# -*- coding: utf-8 -*-
# @Author: WUXIANGCHAO
# @Date:   2025-07-13 22:15:30
# @Last Modified by:   Gemini
# @Last Modified time: 2025-07-29 13:10:00

# 1. Data Configuration
data:
  root_path: "./data/kitti"
  class_names: ["Car", "Pedestrian", "Cyclist"]
  point_cloud_range: [-50, -40, -3, 50, 40, 1]
  voxel_size: [0.05, 0.05, 0.1]
  max_points_per_voxel: 5
  max_number_of_voxels: 40000
  test_max_number_of_voxels: 40000

# 2. Model Configuration
model:
  input_channels: 4

  # 2D BEV骨干网 (类FPN结构)
  bev_backbone:
    in_channels: 384
    layer_channels: [128, 256]
    upsample_channels: [128, 128]
    output_channels: 256

  # 稠密化头的配置
  densification_head:
    num_points_to_predict: 10

  # 检测头的配置
  detection_head:
    in_channels: 256
    tasks:
      - class_names: ["Car"]
      - class_names: ["Pedestrian", "Cyclist"]

# 3. Loss Configuration
loss:
  dense_weight: 0.5
  detect_weight: 1.0
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2.0
  l1_loss_weight: 1.0
  iou_loss_weight: 1.5

# 4. Training Configuration
training:
  epochs: 200
  batch_size: 64
  lr: 0.005
  optimizer: "AdamW"
  lr_scheduler: "OneCycleLR"
  grad_norm_clip: 10
  num_workers: 16
